//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_DictionaryInfo
    {
        public DB_DictionaryInfo()
        {
            this.DB_Sell = new HashSet<DB_Sell>();
            this.DB_SellDetail = new HashSet<DB_SellDetail>();
            this.DB_ButcherProcess = new HashSet<DB_ButcherProcess>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string FK_DictionaryCategory { get; set; }
        public string OperatorCode { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime OperatorTime { get; set; }
        public string Remark { get; set; }
    
        public virtual DB_DictionaryCategory DB_DictionaryCategory { get; set; }
        public virtual ICollection<DB_Sell> DB_Sell { get; set; }
        public virtual ICollection<DB_SellDetail> DB_SellDetail { get; set; }
        public virtual ICollection<DB_ButcherProcess> DB_ButcherProcess { get; set; }
    }
}
