//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Menus
    {
        public DB_Menus()
        {
            this.DB_Menus1 = new HashSet<DB_Menus>();
        }
    
        public string PK_Code { get; set; }
        public string Name { get; set; }
        public string FK_PCode { get; set; }
        public string Url { get; set; }
        public string IconCls { get; set; }
        public int MenuType { get; set; }
        public Nullable<int> Orders { get; set; }
    
        public virtual ICollection<DB_Menus> DB_Menus1 { get; set; }
        public virtual DB_Menus DB_Menus2 { get; set; }
    }
}
