//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_UserInfo
    {
        public DB_UserInfo()
        {
            this.DB_ArrearsDetail = new HashSet<DB_ArrearsDetail>();
            this.DB_CreditDetail = new HashSet<DB_CreditDetail>();
        }
    
        public int Id { get; set; }
        public string UserNo { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<DB_ArrearsDetail> DB_ArrearsDetail { get; set; }
        public virtual ICollection<DB_CreditDetail> DB_CreditDetail { get; set; }
    }
}
