//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DB_Manager> DB_Manager { get; set; }
        public DbSet<DB_Menus> DB_Menus { get; set; }
        public DbSet<DB_DictionaryCategory> DB_DictionaryCategory { get; set; }
        public DbSet<DB_DictionaryInfo> DB_DictionaryInfo { get; set; }
        public DbSet<DB_Sell> DB_Sell { get; set; }
        public DbSet<DB_SellDetail> DB_SellDetail { get; set; }
        public DbSet<DB_ButcherProcess> DB_ButcherProcess { get; set; }
        public DbSet<DB_UserInfo> DB_UserInfo { get; set; }
        public DbSet<DB_ArrearsDetail> DB_ArrearsDetail { get; set; }
        public DbSet<DB_CreditDetail> DB_CreditDetail { get; set; }
    }
}
